import mongoose from "mongoose";
import { Ticket } from "../models/Ticket";
import SLAModel, { SLA_STATUSES } from "../models/SLA";
import { syncDueSLAEscalations } from "./sla.service";
import logger from "../config/logger";
import { ApiError } from "../utils/ApiError";

/* -------------------------------------------------------------------------- */
/* Types                                                                      */
/* -------------------------------------------------------------------------- */

export interface DashboardMetrics {
  totalTickets: number;
  openTickets: number;
  resolvedToday: number;
  slaBreaches: number;
  avgResolutionTime: number;
  /** % of resolved/closed tickets that did NOT breach the 24h SLA window. 100 when none have closed yet. */
  slaCompliance: number;
  /** 0-100 score derived from recorded 1-5 customer ratings (avgRating/5*100). Null when no ratings exist yet. */
  customerSatisfaction: number | null;
}

export interface TrendPoint {
  _id: string;
  count: number;

  /*
   * FIX: added three new series to the same per-day point so the frontend
   * can plot all four lines off a single `trends` array, keyed by date.
   *
   * - resolvedCount: tickets whose resolved_date falls on this day
   *   (event-based, same shape as `count`, just keyed off a different
   *   immutable-once-set date field — accurate going forward).
   * - closedCount: same idea, keyed off closed_date.
   * - openCount: NOT an event count. This is a running balance —
   *   "how many tickets were open as of the end of this day" —
   *   computed as (created on/before day) - (resolved on/before day)
   *   - (closed on/before day). See computeOpenTrend() below.
   */
  resolvedCount: number;
  closedCount: number;
  openCount: number;
}

export interface DistributionPoint {
  _id: string;
  value: number;
}

export interface AgentPerformancePoint {
  _id: string;
  totalTickets: number;
  resolvedTickets: number;
  pendingTickets: number;
}

export interface ActivityItem {
  ticketNumber?: string;
  title?: string;
  customer?: string;
  assignedTo?: string;
  category?: string;
  subCategory?: string;
  status?: string;
  updatedAt?: string;
  createdAt?: string;
}

export interface SLALevelHealthPoint {
  level: number;
  count: number;
  breached: number;
  healthy: number;
}

export interface DashboardData {
  metrics: DashboardMetrics;
  charts: {
    trends: TrendPoint[];
    categoryDistribution: DistributionPoint[];
    subCategoryDistribution: DistributionPoint[];
    statusDistribution: DistributionPoint[];
    agentPerformance: AgentPerformancePoint[];
    /** Per-level (1-5) SLA health breakdown, plus a combined score in metrics.slaCompliance. */
    slaByLevel: SLALevelHealthPoint[];
  };
  activity: ActivityItem[];
}

/* -------------------------------------------------------------------------- */
/* Constants                                                                  */
/* -------------------------------------------------------------------------- */

const DEFAULT_TREND_DAYS = 30 as const;
const MAX_TREND_DAYS = 366 as const;

const OPEN_STATUSES = ["new", "open", "pending", "reopened", "request_clarification", "in_progress"] as const;
const CLOSED_STATUSES = ["resolved", "closed"] as const;

/* -------------------------------------------------------------------------- */
/* Helpers                                                                    */
/* -------------------------------------------------------------------------- */

const safeNumber = (value: unknown): number => {
  return typeof value === "number" && Number.isFinite(value) ? value : 0;
};

/*
 * FIX: previously used `new Date()` + `setHours(0,0,0,0)`, which clamps to
 * LOCAL midnight (server timezone) — but MongoDB's $dateToString buckets
 * days in UTC by default. On a server running ahead of UTC (e.g. IST,
 * UTC+5:30), local midnight is still the previous UTC day, so
 * `.toISOString().slice(0,10)` on it yields YESTERDAY's date string. Every
 * day-key generated by lastNDays() was then one day behind the Mongo
 * aggregation's actual UTC-bucketed createdDateFormatted/resolvedDateFormatted/
 * closedDateFormatted, so "today's" ticket activity matched no day in the
 * `days[]` window and silently dropped out of created/resolved/closed —
 * only `openCount` survived, since that branch is live-queried independent
 * of date-string matching. Computing midnight directly in UTC fixes the
 * mismatch at the source.
 */
const startOfToday = (): Date => {
  const d = new Date();
  return new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate()));
};

const formatDate = (d: Date): string => d.toISOString().slice(0, 10);

/** Last N calendar day strings (UTC), oldest first, ending today (inclusive). */
function lastNDays(n: number): string[] {
  const days: string[] = [];
  const cursor = startOfToday();
  for (let i = n - 1; i >= 0; i--) {
    const d = new Date(cursor);
    d.setUTCDate(d.getUTCDate() - i);
    days.push(formatDate(d));
  }
  return days;
}

/* -------------------------------------------------------------------------- */
/* Aggregation Result Shape                                                  */
/* -------------------------------------------------------------------------- */

interface RawMetrics {
  totalTickets?: number;
  openTickets?: number;
  resolvedToday?: number;
  slaBreaches?: number;
  avgResolutionTime?: number;
  slaTrackedCount?: number;
}

interface CreatedCountPoint {
  _id: string;
  count: number;
}

interface DateOnlyPoint {
  _id: string;
  count: number;
}

interface CustomerSatisfactionPoint {
  avgRating: number;
  count: number;
}

interface SLAByLevelPoint {
  _id: number;
  count: number;
  breached: number;
}

interface AggregationResult {
  metrics?: RawMetrics[];

  createdTrend?: CreatedCountPoint[];
  resolvedTrend?: DateOnlyPoint[];
  closedTrend?: DateOnlyPoint[];

  categoryDistribution?: DistributionPoint[];
  subCategoryDistribution?: DistributionPoint[];
  statusDistribution?: DistributionPoint[];
  agentPerformance?: AgentPerformancePoint[];
  customerSatisfaction?: CustomerSatisfactionPoint[];
  recentActivity?: ActivityItem[];
  slaByLevel?: SLAByLevelPoint[];
}

/* -------------------------------------------------------------------------- */
/* Open-trend (cumulative running balance)                                   */
/* -------------------------------------------------------------------------- */

/**
 * "Open as of EOD day X" = tickets created on/before X
 *                          minus tickets resolved on/before X
 *                          minus tickets closed on/before X.
 *
 * This is NOT an event count like createdTrend/resolvedTrend/closedTrend —
 * it's a running balance, so it can't come from a simple $group by day.
 * We instead fetch per-day created/resolved/closed counts across the full
 * ticket history (not just the last 30 days, since older tickets still
 * contribute to the running total) and accumulate.
 *
 * Today's value is always computed fresh from current ticket state on
 * every request (no caching), so reloading mid-day after resolving a
 * ticket reflects the change immediately, per spec.
 */
async function computeOpenTrend(
  days: string[],
): Promise<Map<string, number>> {
  const earliestDay = days[0];
  const earliestDate = new Date(`${earliestDay}T00:00:00.000Z`);

  // Cumulative counts as of the day BEFORE our window starts, so the
  // running balance inside the window is correct even though older
  // history isn't displayed.
  const [createdBefore, resolvedBefore, closedBefore] = await Promise.all([
    Ticket.countDocuments({ created_date: { $lt: earliestDate } }),
    Ticket.countDocuments({ resolved_date: { $lt: earliestDate, $ne: null } }),
    Ticket.countDocuments({ closed_date: { $lt: earliestDate, $ne: null } }),
  ]);

  // Per-day deltas within the window, for each of the three event types.
  const [createdDeltas, resolvedDeltas, closedDeltas] = await Promise.all([
    Ticket.aggregate<DateOnlyPoint>([
      { $match: { created_date: { $gte: earliestDate } } },
      {
        $group: {
          _id: { $dateToString: { format: "%Y-%m-%d", date: "$created_date" } },
          count: { $sum: 1 },
        },
      },
    ]),
    Ticket.aggregate<DateOnlyPoint>([
      { $match: { resolved_date: { $gte: earliestDate, $ne: null } } },
      {
        $group: {
          _id: { $dateToString: { format: "%Y-%m-%d", date: "$resolved_date" } },
          count: { $sum: 1 },
        },
      },
    ]),
    Ticket.aggregate<DateOnlyPoint>([
      { $match: { closed_date: { $gte: earliestDate, $ne: null } } },
      {
        $group: {
          _id: { $dateToString: { format: "%Y-%m-%d", date: "$closed_date" } },
          count: { $sum: 1 },
        },
      },
    ]),
  ]);

  const createdMap = new Map(createdDeltas.map((d) => [d._id, d.count]));
  const resolvedMap = new Map(resolvedDeltas.map((d) => [d._id, d.count]));
  const closedMap = new Map(closedDeltas.map((d) => [d._id, d.count]));

  const today = formatDate(startOfToday());

  const result = new Map<string, number>();
  let running = createdBefore - resolvedBefore - closedBefore;

  for (const day of days) {
    if (day === today) {
      // FIX: today is never trusted to the per-day aggregation above —
      // computed directly from live current-state counts so a reload
      // immediately after resolving a ticket reflects instantly, with
      // no dependency on resolved_date/closed_date bucket timing.
      const [liveOpen] = await Promise.all([
        Ticket.countDocuments({ tkt_status: { $in: OPEN_STATUSES } }),
      ]);
      result.set(day, liveOpen);
      continue;
    }

    running +=
      (createdMap.get(day) ?? 0) -
      (resolvedMap.get(day) ?? 0) -
      (closedMap.get(day) ?? 0);

    result.set(day, Math.max(0, running));
  }

  return result;
}

/* -------------------------------------------------------------------------- */
/* Service                                                                    */
/* -------------------------------------------------------------------------- */

export interface DashboardDataOptions {
  /**
   * Number of trailing calendar days to include in `charts.trends`, clamped
   * to [1, MAX_TREND_DAYS]. Ignored if `full` is true. Defaults to 30 to
   * preserve existing behavior for any caller that doesn't pass options.
   */
  days?: number;

  /**
   * When true, the trend window spans from the date of the earliest ticket
   * in the system through today, instead of a fixed trailing window.
   */
  full?: boolean;
}

async function resolveTrendDays(
  options: DashboardDataOptions,
): Promise<string[]> {
  if (options.full) {
    const earliest = await Ticket.findOne({})
      .sort({ created_date: 1 })
      .select({ created_date: 1 })
      .lean<{ created_date: Date } | null>();

    if (!earliest?.created_date) {
      // No tickets at all yet — fall back to a single-day window (today)
      // so downstream code always has at least one point to render.
      return lastNDays(1);
    }

    const msPerDay = 1000 * 60 * 60 * 24;
    const earliestDate = new Date(earliest.created_date);
    const earliestUtcMidnight = Date.UTC(
      earliestDate.getUTCFullYear(),
      earliestDate.getUTCMonth(),
      earliestDate.getUTCDate(),
    );
    const spanDays =
      Math.floor((startOfToday().getTime() - earliestUtcMidnight) / msPerDay) + 1;

    return lastNDays(Math.min(Math.max(spanDays, 1), MAX_TREND_DAYS));
  }

  const requested = options.days ?? DEFAULT_TREND_DAYS;
  const clamped = Math.min(Math.max(Math.floor(requested) || 1, 1), MAX_TREND_DAYS);
  return lastNDays(clamped);
}

export async function getDashboardData(
  options: DashboardDataOptions = {},
): Promise<DashboardData> {
  const startOfDay = startOfToday();
  const days = await resolveTrendDays(options);
  const windowStart = new Date(`${days[0]}T00:00:00.000Z`);

  logger.info("[DASHBOARD_SERVICE] aggregation_started");

  // Bring any overdue SLA trackers up to date before reading breach counts —
  // see sla.service.ts's syncDueSLAEscalations() for why this replaces the
  // old SLA_HOURS=24 hardcoded re-derivation below.
  await syncDueSLAEscalations();

  const [result] = await Ticket.aggregate<AggregationResult>([
    /*
     * FIX: previously computed SLA breach inline with a flat SLA_HOURS=24
     * constant applied to every ticket regardless of priority — completely
     * disconnected from the real SLA collection (which tracks per-priority,
     * multi-level escalating limits via sla.service.ts). That made dashboard
     * and analytics each invent their own answer and disagree. Now we join
     * against the actual SLA tracker per ticket instead.
     */
    {
      $lookup: {
        from: "slas",
        localField: "_id",
        foreignField: "ticketId",
        as: "slaDoc",
      },
    },
    {
      $addFields: {
        slaStatus: { $arrayElemAt: ["$slaDoc.status", 0] },
        slaLevel: { $arrayElemAt: ["$slaDoc.currentLevel", 0] },
      },
    },
    {
      $addFields: {
        resolutionTimeHours: {
          $cond: [
            { $in: ["$tkt_status", CLOSED_STATUSES] },
            {
              $divide: [
                { $subtract: ["$update_date", "$created_date"] },
                1000 * 60 * 60,
              ],
            },
            null,
          ],
        },

        slaBreachedComputed: {
          $in: ["$slaStatus", [SLA_STATUSES.BREACHED, SLA_STATUSES.SLA_VIOLATED]],
        },

        createdDateFormatted: {
          $dateToString: { format: "%Y-%m-%d", date: "$created_date" },
        },
        resolvedDateFormatted: {
          $cond: [
            { $ne: ["$resolved_date", null] },
            { $dateToString: { format: "%Y-%m-%d", date: "$resolved_date" } },
            null,
          ],
        },
        closedDateFormatted: {
          $cond: [
            { $ne: ["$closed_date", null] },
            { $dateToString: { format: "%Y-%m-%d", date: "$closed_date" } },
            null,
          ],
        },
      },
    },

    {
      $facet: {
        metrics: [
          {
            $group: {
              _id: null,
              totalTickets: { $sum: 1 },
              openTickets: {
                $sum: { $cond: [{ $in: ["$tkt_status", OPEN_STATUSES] }, 1, 0] },
              },
              /*
               * BUG FIX: previously used closedTicketsCount as denominator, which
               * returned 100% whenever breached tickets were still open (not yet
               * closed), because closedTicketsCount=0 triggered the 100% guard.
               * Correct denominator is tickets that have an SLA tracker attached
               * (slaTrackedCount). A breach is a breach regardless of ticket status.
               */
              slaTrackedCount: {
                $sum: { $cond: [{ $ifNull: ["$slaStatus", false] }, 1, 0] },
              },
              resolvedToday: {
                $sum: {
                  $cond: [
                    {
                      $and: [
                        { $in: ["$tkt_status", CLOSED_STATUSES] },
                        { $gte: ["$update_date", startOfDay] },
                      ],
                    },
                    1,
                    0,
                  ],
                },
              },
              slaBreaches: { $sum: { $cond: ["$slaBreachedComputed", 1, 0] } },
              avgResolutionTime: { $avg: "$resolutionTimeHours" },
            },
          },
        ],

        /*
         * Per-level SLA health: how many ACTIVE tickets currently sit at
         * each of the 5 escalation levels, plus how many of those are
         * already breached at that level. Powers the "all 5 levels
         * individually visible" SLA health view on the frontend.
         */
        slaByLevel: [
          { $match: { slaLevel: { $ne: null } } },
          {
            $group: {
              _id: "$slaLevel",
              count: { $sum: 1 },
              breached: {
                $sum: {
                  $cond: [
                    { $in: ["$slaStatus", [SLA_STATUSES.BREACHED, SLA_STATUSES.SLA_VIOLATED]] },
                    1,
                    0,
                  ],
                },
              },
            },
          },
          { $sort: { _id: 1 } },
        ],

        createdTrend: [
          { $match: { created_date: { $gte: windowStart } } },
          { $group: { _id: "$createdDateFormatted", count: { $sum: 1 } } },
          { $sort: { _id: 1 } },
        ],

        resolvedTrend: [
          {
            $match: {
              resolvedDateFormatted: { $ne: null },
              resolved_date: { $gte: windowStart },
            },
          },
          { $group: { _id: "$resolvedDateFormatted", count: { $sum: 1 } } },
          { $sort: { _id: 1 } },
        ],

        closedTrend: [
          {
            $match: {
              closedDateFormatted: { $ne: null },
              closed_date: { $gte: windowStart },
            },
          },
          { $group: { _id: "$closedDateFormatted", count: { $sum: 1 } } },
          { $sort: { _id: 1 } },
        ],

        categoryDistribution: [
          {
            $group: {
              _id: { $ifNull: ["$cat_id", "Uncategorized"] },
              value: { $sum: 1 },
            },
          },
          { $sort: { value: -1 } },
        ],

        subCategoryDistribution: [
          {
            $group: {
              _id: { $ifNull: ["$sub_cat_id", "Unknown"] },
              value: { $sum: 1 },
            },
          },
          { $sort: { value: -1 } },
        ],

        agentPerformance: [
          {
            $group: {
              _id: { $ifNull: ["$tkt_user", "Unassigned"] },
              totalTickets: { $sum: 1 },
              resolvedTickets: {
                $sum: { $cond: [{ $in: ["$tkt_status", CLOSED_STATUSES] }, 1, 0] },
              },
              pendingTickets: {
                $sum: { $cond: [{ $eq: ["$tkt_status", "pending"] }, 1, 0] },
              },
            },
          },
          { $sort: { resolvedTickets: -1 } },
        ],

        statusDistribution: [
          {
            $group: {
              _id: { $ifNull: ["$tkt_status", "unknown"] },
              value: { $sum: 1 },
            },
          },
          { $sort: { value: -1 } },
        ],

        /*
         * FIX: customerSatisfaction previously didn't exist on this
         * aggregation at all — DashboardMetrics never carried the field,
         * so the Analytics page's CSAT card always fell back to its
         * client-side default of 0. customer_satisfaction is a 1-5 rating
         * an agent records on the ticket (see Ticket model); this averages
         * whatever's been recorded and expresses it as a 0-100 score to
         * match the card's percentage display (rating/5 * 100).
         */
        customerSatisfaction: [
          { $match: { customer_satisfaction: { $ne: null } } },
          {
            $group: {
              _id: null,
              avgRating: { $avg: "$customer_satisfaction" },
              count: { $sum: 1 },
            },
          },
        ],

        recentActivity: [
          { $sort: { update_date: -1 } },
          { $limit: 10 },
          {
            $project: {
              _id: 0,
              ticketNumber: { $toString: "$_id" },
              title: { $ifNull: ["$email_subject", "Untitled Ticket"] },
              customer: { $ifNull: ["$tkt_customer_name", "Unknown Customer"] },
              assignedTo: { $ifNull: ["$tkt_user", "Unassigned"] },
              category: { $ifNull: ["$cat_id", "Uncategorized"] },
              subCategory: { $ifNull: ["$sub_cat_id", "Unknown"] },
              status: { $ifNull: ["$tkt_status", "unknown"] },
              updatedAt: "$update_date",
              createdAt: "$created_date",
            },
          },
        ],
      },
    },
  ]);

  const data = result ?? {};
  const metricsRaw = data.metrics?.[0] ?? {};

  const slaBreaches = safeNumber(metricsRaw.slaBreaches);
  const slaTrackedCount = safeNumber(metricsRaw.slaTrackedCount);

  // BUG FIX: previously divided by closedTicketsCount, which returned 100%
  // whenever breached tickets were still open (closedTicketsCount=0 guard
  // short-circuited to 100). Now divides by slaTrackedCount — every ticket
  // that has an SLA tracker, regardless of whether it is still open.
  const slaCompliance =
    slaTrackedCount === 0
      ? 100
      : Number(
          (((slaTrackedCount - slaBreaches) / slaTrackedCount) * 100).toFixed(1),
        );

  const csatPoint = data.customerSatisfaction?.[0];
  const customerSatisfaction =
    csatPoint && csatPoint.count > 0
      ? Number(((csatPoint.avgRating / 5) * 100).toFixed(1))
      : null;

  const metrics: DashboardMetrics = {
    totalTickets: safeNumber(metricsRaw.totalTickets),
    openTickets: safeNumber(metricsRaw.openTickets),
    resolvedToday: safeNumber(metricsRaw.resolvedToday),
    slaBreaches,
    avgResolutionTime: safeNumber(metricsRaw.avgResolutionTime),
    slaCompliance,
    customerSatisfaction,
  };

  /* ── Merge the three event trends + the computed open-trend into one series, one point per day ── */

  const createdMap = new Map(
    (data.createdTrend ?? []).map((p) => [p._id, p.count]),
  );
  const resolvedMap = new Map(
    (data.resolvedTrend ?? []).map((p) => [p._id, p.count]),
  );
  const closedMap = new Map(
    (data.closedTrend ?? []).map((p) => [p._id, p.count]),
  );
  const openMap = await computeOpenTrend(days);

  const trends: TrendPoint[] = days.map((day) => ({
    _id: day,
    count: createdMap.get(day) ?? 0,
    resolvedCount: resolvedMap.get(day) ?? 0,
    closedCount: closedMap.get(day) ?? 0,
    openCount: openMap.get(day) ?? 0,
  }));

  // All 5 levels always present (zero-filled) so the frontend can render a
  // consistent 5-bar/5-segment view even when some levels have no tickets.
  const slaByLevelMap = new Map(
    (data.slaByLevel ?? []).map((p) => [p._id, p]),
  );
  const slaByLevel: SLALevelHealthPoint[] = [1, 2, 3, 4, 5].map((level) => {
    const point = slaByLevelMap.get(level);
    const count = point?.count ?? 0;
    const breached = point?.breached ?? 0;
    return { level, count, breached, healthy: count - breached };
  });

  return {
    metrics,
    charts: {
      trends,
      categoryDistribution: data.categoryDistribution ?? [],
      subCategoryDistribution: data.subCategoryDistribution ?? [],
      statusDistribution: data.statusDistribution ?? [],
      agentPerformance: data.agentPerformance ?? [],
      slaByLevel,
    },
    activity: data.recentActivity ?? [],
  };
}
/* ============================================================
 * AGENT PERFORMANCE — list + single
 * ============================================================ */

export interface AgentPerformanceSummary {
  agentId: string;
  name: string;
  email: string;
  role: string;
  totalTickets: number;
  resolvedTickets: number;
  pendingTickets: number;
  openTickets: number;
  avgResolutionHours: number | null;
  avgResponseMinutes: number | null;
  slaBreaches: number;
  csatAvg: number | null;
  fcrRate: number | null;
  reopenedCount: number;
}

export async function getAgentPerformanceList(
  options?: { period?: string },
): Promise<AgentPerformanceSummary[]> {
  const { User } = await import("../models/User");
  const { Ticket } = await import("../models/Ticket");

  const agents = await User.find({
    role: { $in: ["agent", "team_lead", "manager", "admin"] },
    isActive: { $ne: false },
  }).select({ _id: 1, name: 1, email: 1, role: 1 }).lean();

  const results: AgentPerformanceSummary[] = await Promise.all(
    agents.map(async (agent) => {
      const agentId = agent._id as mongoose.Types.ObjectId;

      const [ticketAgg, slaBreaches] = await Promise.all([
        Ticket.aggregate([
          { $match: { tkt_assigned_to: agentId, merged_into: null } },
          {
            $group: {
              _id: null,
              total: { $sum: 1 },
              resolved: { $sum: { $cond: [{ $in: ["$tkt_status", ["resolved", "closed"]] }, 1, 0] } },
              pending: { $sum: { $cond: [{ $eq: ["$tkt_status", "pending"] }, 1, 0] } },
              open: { $sum: { $cond: [{ $in: ["$tkt_status", ["open", "new", "reopened", "request_clarification"]] }, 1, 0] } },
              reopened: { $sum: { $cond: [{ $eq: ["$was_reopened", true] }, 1, 0] } },
              avgResolutionMs: {
                $avg: {
                  $cond: [
                    { $and: [{ $ne: ["$resolved_date", null] }, { $ne: ["$created_date", null] }] },
                    { $subtract: ["$resolved_date", "$created_date"] },
                    null,
                  ],
                },
              },
              avgResponseMs: {
                $avg: {
                  $cond: [
                    { $ne: ["$first_response_at", null] },
                    { $subtract: ["$first_response_at", "$created_date"] },
                    null,
                  ],
                },
              },
              csatSum: { $sum: { $ifNull: ["$customer_satisfaction", 0] } },
              csatCount: { $sum: { $cond: [{ $ne: ["$customer_satisfaction", null] }, 1, 0] } },
            },
          },
        ]),
        Ticket.aggregate([
          { $match: { tkt_assigned_to: agentId, merged_into: null } },
          { $lookup: { from: "slas", localField: "_id", foreignField: "ticketId", as: "sla" } },
          { $match: { "sla.status": { $in: ["breached", "sla_violated"] } } },
          { $count: "total" },
        ]).then((r) => r[0]?.total ?? 0),
      ]);

      const agg = ticketAgg[0] ?? {};
      const total = agg.total ?? 0;
      const resolved = agg.resolved ?? 0;
      const fcr = total > 0 && agg.reopened != null
        ? Math.round(((resolved - (agg.reopened ?? 0)) / Math.max(resolved, 1)) * 100)
        : null;

      return {
        agentId: agentId.toString(),
        name: agent.name,
        email: agent.email,
        role: agent.role,
        totalTickets: total,
        resolvedTickets: resolved,
        pendingTickets: agg.pending ?? 0,
        openTickets: agg.open ?? 0,
        reopenedCount: agg.reopened ?? 0,
        avgResolutionHours: agg.avgResolutionMs ? Math.round(agg.avgResolutionMs / 3600000 * 10) / 10 : null,
        avgResponseMinutes: agg.avgResponseMs ? Math.round(agg.avgResponseMs / 60000 * 10) / 10 : null,
        slaBreaches: slaBreaches,
        csatAvg: agg.csatCount > 0 ? Math.round((agg.csatSum / agg.csatCount) * 10) / 10 : null,
        fcrRate: fcr,
      };
    }),
  );

  return results.sort((a, b) => b.resolvedTickets - a.resolvedTickets);
}

export async function getAgentPerformanceById(
  agentId: string,
): Promise<AgentPerformanceSummary & { recentTickets: unknown[] }> {
  const { User } = await import("../models/User");
  const { Ticket } = await import("../models/Ticket");

  const agent = await User.findById(agentId).select({ _id: 1, name: 1, email: 1, role: 1 }).lean();
  if (!agent) throw new ApiError(404, "Agent not found");

  const oid = new mongoose.Types.ObjectId(agentId);

  const summaries = await getAgentPerformanceList();
  const found = summaries.find((s) => s.agentId === agentId) ?? {
    agentId, name: agent.name, email: agent.email, role: agent.role,
    totalTickets: 0, resolvedTickets: 0, pendingTickets: 0, openTickets: 0,
    reopenedCount: 0, avgResolutionHours: null, avgResponseMinutes: null,
    slaBreaches: 0, csatAvg: null, fcrRate: null,
  };

  const recentTickets = await Ticket.find({ tkt_assigned_to: oid, merged_into: null })
    .select({ tkt_number: 1, email_subject: 1, tkt_status: 1, color_code: 1, created_date: 1, resolved_date: 1 })
    .sort({ update_date: -1 })
    .limit(10)
    .lean();

  return { ...found, recentTickets };
}